super_drag_and_drop/example/lib/main.dart, super_drag_and_drop/lib/super_drag_and_drop.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/30
=> feat: super_drag_and_drop: reexport formats from super_clipboard

super_native_extensions/rust/src/darwin/macos/drag.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/42
=> fix: window dragging on macos with full size content view

super_clipboard/lib/src/formats_base.dart, super_clipboard/lib/src/standard_formats.dart, super_native_extensions/rust/Cargo.lock, super_native_extensions/rust/Cargo.toml
Fixes https://github.com/superlistapp/super_native_extensions/issues/56, https://github.com/superlistapp/super_native_extensions/issues/29.
=> feat: declare more well-known formats

super_native_extensions/lib/src/web/drop.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/65
=> fix: regression when dropping plain text on web

super_native_extensions/rust/src/win32/data_object.rs, super_native_extensions/rust/src/win32/virtual_file_stream.rs
Some OLE applications misbehave and request the stream when entering drag without intention to read from the stream. This PR will delay making the virtual file request until the client actually tries to stat or read from the stream.
The application requesting stream can be reproduced when dragging over Windows Terminal (1.16.10262.0)
=> feat: [windows] delay virtual file request until IStream is read

super_native_extensions/lib/src/web/clipboard_api.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/71
=> fix: clipboard copy on web in release mode

super_native_extensions/rust/src/darwin/macos/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/79
=> feat: [macos] receiving virtual files from outlook attachments

super_native_extensions/rust/src/win32/data_object.rs, super_native_extensions/rust/src/win32/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/86.
=> fix: [windows] pasting files from explorer

super_native_extensions/rust/src/darwin/ios/alpha_to_path.rs, super_native_extensions/rust/src/darwin/ios/drag.rs, super_native_extensions/rust/src/darwin/ios/mod.rs
This should significantly improve shadow fidelity on iOS.
=> feat: [ios] use real shadow path instead of layer shadow

super_native_extensions/lib/src/web/drop.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/98
=> fix: [web] dropping over platform views not working

super_clipboard/README.md, super_clipboard/example/pubspec.lock, super_drag_and_drop/README.md, super_drag_and_drop/example/ios/Podfile.lock, super_drag_and_drop/example/pubspec.lock, super_keyboard_layout/example/pubspec.lock, super_native_extensions/android/src/main/java/com/superlist/super_native_extensions/ClipDataHelper.java, super_native_extensions/android/src/main/java/com/superlist/super_native_extensions/DragDropHelper.java, super_native_extensions/pubspec.yaml, super_native_extensions/rust/Cargo.lock, super_native_extensions/rust/Cargo.toml, super_native_extensions/rust/src/android/drag.rs, super_native_extensions/rust/src/android/drop.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/112
=> fix: [android] build failing with proguard enabled

super_native_extensions/rust/src/win32/data_object.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/116
=> fix: [win] rewind OLE streams before reading

super_native_extensions/rust/src/darwin/common.rs, super_native_extensions/rust/src/darwin/ios/reader.rs, super_native_extensions/rust/src/darwin/macos/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/132
=> fix: pasting text with semicolon on macOS

super_context_menu/lib/src/mobile.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/140
=> fix: context menu in list view not working on iOS

super_clipboard/README.md, super_context_menu/README.md, super_drag_and_drop/README.md, super_keyboard_layout/README.md
NDK is now installed automatically during build and the docs should reflect that.
Fixes https://github.com/superlistapp/super_native_extensions/issues/143
=> docs: update NDK installation information

super_clipboard/README.md, super_drag_and_drop/README.md
Fixes https://github.com/superlistapp/super_native_extensions/issues/70
=> docs: [android] mention minSdkVersion in readme

super_native_extensions/rust/src/darwin/macos/menu.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/126
=> fix: [macos] control key stuck after context menu closed

super_context_menu/lib/src/scaffold/desktop/menu_container.dart, super_context_menu/lib/src/scaffold/desktop/menu_widget.dart
https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown
https://height.app/blog/guide-to-build-context-menus
https://github.com/superlistapp/super_native_extensions/assets/96958/4bad53b2-f9a2-460f-99d5-7fa712897772
=> feat: implement safe triangle for desktop menu

super_clipboard/lib/src/writer.dart, super_clipboard/lib/super_clipboard.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/154
=> fix: correct imports and add missing exports

super_native_extensions/rust/src/win32/common.rs, super_native_extensions/rust/src/win32/data_object.rs, super_native_extensions/rust/src/win32/drop.rs, super_native_extensions/rust/src/win32/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/158
=> fix: [windows] properly handle data objects that don't support async capability

super_native_extensions/rust/src/win32/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/168
=> fix: [windows] handle null terminator in CF_UNICODETEXT

super_native_extensions/rust/Cargo.lock
Fixes https://github.com/superlistapp/super_native_extensions/issues/166
=> fix: update rust dependencies

.github/workflows/precompile_binaries.yml, check_precompiled.sh, melos.yaml, super_clipboard/README.md, super_clipboard/example/pubspec.lock, super_context_menu/README.md, super_context_menu/example/pubspec.lock, super_drag_and_drop/README.md, super_drag_and_drop/example/pubspec.lock, super_keyboard_layout/README.md, super_keyboard_layout/example/pubspec.lock, super_native_extensions/pubspec.yaml, super_native_extensions/rust/Cargo.toml, super_native_extensions/rust/cargokit.yaml
Fixes https://github.com/superlistapp/super_native_extensions/issues/174
=> feat! enable precompiled binaries

super_clipboard/lib/src/format_conversions.dart, super_clipboard/lib/src/standard_formats.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/188
=> feat[clipboard]: signal UTF-8 in HTML snippet

super_native_extensions/rust/src/darwin/ios/menu.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/204
=> fix: [iOS] crash when deferred image is set too quickly

super_clipboard/lib/src/standard_formats.dart
Adds support for epub and markdown files
=> feat: add support for epub and md

super_context_menu/lib/src/desktop.dart, super_context_menu/lib/src/menu_internal.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/216
=> fix: properly handle overlapping menu widgets

super_native_extensions/pubspec.yaml
Having trouble using   flutter_rust_bridge: ^1.82.3
=> Update uuid version to 4.x.x

super_context_menu/lib/src/desktop.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/218
=> fix: regression when context menu sometimes does not show

super_clipboard/lib/src/format_conversions.dart, super_clipboard/lib/src/reader_internal.dart, super_context_menu/lib/src/scaffold/desktop/menu_container.dart, super_drag_and_drop/lib/src/drag_internal.dart, super_native_extensions/rust/src/android/drop.rs
also remove some hacks to support flutter stable previous version
=> chore: make clippy and analyzer happy

super_native_extensions/rust/Cargo.lock, super_native_extensions/rust/Cargo.toml, super_native_extensions/rust/src/darwin/common.rs, super_native_extensions/rust/src/darwin/ios/alpha_to_path.rs, super_native_extensions/rust/src/darwin/ios/data_provider.rs, super_native_extensions/rust/src/darwin/ios/drag.rs, super_native_extensions/rust/src/darwin/ios/drag_common.rs, super_native_extensions/rust/src/darwin/ios/drop.rs, super_native_extensions/rust/src/darwin/ios/menu.rs, super_native_extensions/rust/src/darwin/ios/mod.rs, super_native_extensions/rust/src/darwin/ios/objc_drop_notifier.rs, super_native_extensions/rust/src/darwin/ios/reader.rs, super_native_extensions/rust/src/darwin/ios/uikit.rs, super_native_extensions/rust/src/darwin/ios/util.rs, super_native_extensions/rust/src/darwin/macos/data_provider.rs, super_native_extensions/rust/src/darwin/macos/drag.rs, super_native_extensions/rust/src/darwin/macos/drag_common.rs, super_native_extensions/rust/src/darwin/macos/drop.rs, super_native_extensions/rust/src/darwin/macos/menu.rs, super_native_extensions/rust/src/darwin/macos/reader.rs, super_native_extensions/rust/src/darwin/macos/util.rs, super_native_extensions/rust/src/darwin/progress_bridge.rs, super_native_extensions/rust/src/drop_manager.rs, super_native_extensions/rust/src/reader_manager.rs, super_native_extensions/rust/src/util.rs, super_native_extensions/rust/src/value_coerce.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/177
=> feat: migrate to objc2

super_native_extensions/rust/src/darwin/common.rs, super_native_extensions/rust/src/darwin/ios/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/252
=> fix: access NSURL within security scope

super_native_extensions/rust/src/win32/reader.rs
Improves https://github.com/superlistapp/super_native_extensions/issues/265
=> feat: [windows] cache file descriptors in reader

super_native_extensions/lib/src/web/js_interop.dart, super_native_extensions/lib/src/web/reader.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/267
=> fix[web]: null pointer exception when accessing entry

super_clipboard/example/pubspec.lock, super_context_menu/example/pubspec.lock, super_native_extensions/rust/src/darwin/common.rs, super_native_extensions/rust/src/darwin/ios/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/270
=> fix: no security scope NSURL access on macos

super_native_extensions/rust/src/darwin/ios/drag.rs, super_native_extensions/rust/src/darwin/ios/drop.rs, super_native_extensions/rust/src/darwin/ios/menu.rs
Fixes panic during hot restart.
=> fix: [ios] store user interaction properly

super_drag_and_drop/lib/src/drop_internal.dart, super_native_extensions/rust/src/win32/reader.rs
Improves https://github.com/superlistapp/super_native_extensions/issues/265
=> feat: improve performance with large number of items

super_clipboard/lib/src/standard_formats.dart
Partially fixes https://github.com/superlistapp/super_native_extensions/issues/275
=> fix: correct GIF uniform type identifier

super_clipboard/example/lib/widget_for_reader.dart, super_clipboard/lib/src/events.dart, super_clipboard/lib/src/reader.dart, super_clipboard/lib/src/reader_internal.dart, super_clipboard/lib/src/system_clipboard.dart, super_drag_and_drop/lib/src/drop.dart, super_drag_and_drop/lib/src/drop_internal.dart, super_native_extensions/lib/src/native/reader_manager.dart, super_native_extensions/lib/src/reader.dart, super_native_extensions/lib/src/reader_manager.dart, super_native_extensions/lib/src/web/reader_manager.dart, super_native_extensions/rust/src/android/reader.rs, super_native_extensions/rust/src/darwin/ios/reader.rs, super_native_extensions/rust/src/darwin/macos/reader.rs, super_native_extensions/rust/src/linux/reader.rs, super_native_extensions/rust/src/reader_manager.rs, super_native_extensions/rust/src/win32/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/265
=> Refactor reading to improve speed with large amount of files

super_clipboard/lib/src/standard_formats.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/304
=> feat: add m4a format definition

super_clipboard/lib/src/standard_formats.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/329
=> feat: add flac and ogg format definitions

super_native_extensions/rust/src/darwin/macos/drag.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/359
=> fix[macOS]: do not intercept rotate and scale events

super_drag_and_drop/lib/src/drag_internal.dart, super_native_extensions/lib/src/drag.dart, super_native_extensions/lib/src/native/drag.dart, super_native_extensions/lib/src/web/drag.dart
Fixes https://github.com/superlistapp/super_native_extensions/pull/377
=> fix: detect drag cancelled on desktop while waiting for data

super_native_extensions/lib/src/gesture/pointer_device_kind.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/332
=> fix: context menu on iPad with universal control

super_native_extensions/rust/src/win32/drop.rs, super_native_extensions/rust/src/win32/reader.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/395
=> fix: panic in ANSI branch of extract_drop_files

super_native_extensions/rust/cargokit.yaml
Fixes https://github.com/superlistapp/super_native_extensions/issues/411
=> fix: do not build release binary with nightly

super_native_extensions/pubspec.yaml
=> Bump device info plus dependency
