super_native_extensions/rust/src/darwin/ios/drag.rs, super_native_extensions/rust/src/darwin/ios/drop.rs, super_native_extensions/rust/src/darwin/ios/util.rs
Fixed by not sending touch events while pumping CFRunLoop when waiting for drag data.
=> fix: rare crash while dragging on iOS

super_native_extensions/lib/src/drop.dart, super_native_extensions/lib/src/native/drop.dart
Otherwise there may be race condition where reader gets destroyed while previous drop event is being in progress.
=> fix: serialize invocation of drop events

super_clipboard/example/windows/runner/main.cpp, super_drag_and_drop/example/windows/runner/main.cpp, super_native_extensions/rust/src/context.rs, super_native_extensions/rust/src/win32/mod.rs, super_native_extensions/rust/src/win32/ole_initializer.rs
Instead of relying on user to do that, the plugin should ensure OLE is initialized.
=> feat: initialize ole on windows

super_native_extensions/rust/src/win32/reader.rs
We should never interact with the stream on main thread (it could deadlock when dealing with our virtual stream) and there already is cached length obtained when constructing `StreamReader`.
=> fix: [windows] use cached length when reading virtual stream

super_drag_and_drop/README.md, super_drag_and_drop/example/lib/main.dart, super_drag_and_drop/lib/src/base_draggable_widget.dart, super_drag_and_drop/lib/src/drag_configuration.dart, super_drag_and_drop/lib/src/drag_internal.dart, super_drag_and_drop/lib/src/draggable_widget.dart, super_drag_and_drop/lib/src/into_raw.dart, super_drag_and_drop/lib/super_drag_and_drop.dart, super_keyboard_layout/example/pubspec.lock, super_native_extensions/lib/src/api_model.dart, super_native_extensions/lib/src/drag.dart, super_native_extensions/lib/src/drag_internal.dart, super_native_extensions/lib/src/native/drag.dart, super_native_extensions/lib/src/web/drag.dart, super_native_extensions/lib/src/widgets/snapshot.dart, super_native_extensions/lib/widgets.dart, super_native_extensions/rust/src/darwin/ios/drag.rs, super_native_extensions/rust/src/win32/reader.rs
This PR introduces `CustomSnapshotWidget` to simplify providing custom drag snapshots.
This is a **breaking change**:
```dart
return DragItemWidget(
dragItemProvider: (snapshot, session) async {
final item = DragItem(
image: await snapshot(),        
localData: {'x': 3, 'y': 4},
);
```
becomes
```dart
return DragItemWidget(
dragItemProvider: (request) async {
final item = DragItem(
image: request.dragImage(),
localData: {'x': 3, 'y': 4},
);
```
To be able to build widget for custom drag avatars wrap `DragItemWidget` inside a `CustomSnapshotWidget`:
```dart
return CustomSnapshotWidget(
builder: (context, type) {
return DragItemWidget(
allowedOperations: () => [DropOperation.copy],
canAddItemToExistingSession: true,
dragItemProvider: provideDragItem,
child: Container(
// Red background for …
```
=> feat! implement custom drag snapshots

super_native_extensions/rust/src/darwin/ios/drag.rs
Even if lift image is not specified we now require separate drag image view because it has small shadow then lift image. Otherwise the lift image shadow will get cropped during drag which looks ugly.
=> fix: [ios] force separate drag image to account for shadow difference

super_native_extensions/rust/src/darwin/ios/drag.rs
It does not seem to be necessary anymore and it was causing delays when transitioning to drag.
Also tweaks the shadow slightly.
=> feat: [ios] remove drag item provider memory leak workaround

super_drag_and_drop/lib/src/draggable_widget.dart
Otherwise Flutter may throw exception if `dragItemsProvider` tries to access unmounted context.
=> fix: cache active items for snapshotter

super_native_extensions/ios/super_native_extensions.podspec, super_native_extensions/macos/super_native_extensions.podspec, super_native_extensions/rust/symbols.txt
```
_OBJC_CLASS_$_SuperNativeExtensionsPlugin
_super_native_extensions_init_message_channel_context
_super_native_extensions_stream_write
_super_native_extensions_stream_close
```
This is the content of `super_native_extensions/rust/symbols.txt`. Though this might work on some architectures, I encountered some build errors when running on x86_64 macOS. On this X86_64 macOS platform, additional symbols were needed, which were very long and weird that it seemed almost impossible to write all symbols that would be needed on different architectures. Also, they make conflicts across architectures if they are written in the same file.
IMO, it would be much better if we just force-load the static library file, including all the symbols already declared.
=> Use force loading instead of manual symbols on iOS and macOS

super_native_extensions/macos/Classes/SuperNativeExtensionsPlugin.m
Caused by double loading menu contents.
=> fix: [macos] assertion when loading deferred menu

super_native_extensions/rust/src/darwin/macos/menu.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/194
=> fix: [macOS] missing image on NSMenuItem with children

super_hot_key/lib/super_hot_key.dart, super_native_extensions/lib/src/hot_key.dart, super_native_extensions/lib/src/native/hot_key.dart, super_native_extensions/rust/src/darwin/macos/hot_key.rs, super_native_extensions/rust/src/darwin/macos/hot_key_sys.rs, super_native_extensions/rust/src/hot_key_manager.rs, super_native_extensions/rust/src/win32/hot_key.rs
This is a breaking change:
`HotKey.create` has been modifies:
- removed `callback` argument
- added `onPressed` and `onReleased` arguments
Fixes https://github.com/superlistapp/super_native_extensions/issues/232
=> feat! Implement HotKey.onReleased

.github/workflows/precompile_binaries.yml
This is to done in order to link to order glibc version.
=> chore: use ubuntu-20.04 for precompiled binaries

super_native_extensions/lib/src/drag_interaction/overlay_layout.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/317
=> fix: fit menu position to bounds after inflating

super_context_menu/lib/src/default_builder/mobile_menu_widget_builder.dart, super_context_menu/lib/src/menu.dart
Calling `DeviceInfoPlugin().deviceInfo` for every instance of `ContextMenuWidget` is expensive if there are multiple ones created during single frame. This adds a static instance accessor to `DefaultMobileMenuWidgetBuilder` to reuse result of a single call to `DeviceInfoPlugin().deviceInfo`.
=> Adds static instance getter to DefaultMobileMenuWidgetBuilder

super_native_extensions/lib/src/gesture/pointer_device_kind.dart
During drag & drop on Android there is single event with wrong pointer device kind causes number of unnecessary rebuilds.
=> fix: ignore unknown pointer device kind

super_native_extensions/android/src/main/java/com/superlist/super_native_extensions/DragDropHelper.java
Using startDragAndDrop instead of startDrag on Android sdk24 and above
just like
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
view.startDragAndDrop(clipData,
new DragShadowBuilder(bitmap, new Point(touchPointX, touchPointY)), new SessionId(dragSessionId),
flags
);
} else {
view.startDrag(clipData,
new DragShadowBuilder(bitmap, new Point(touchPointX, touchPointY)), new SessionId(dragSessionId),
flags
);
}
```
fixes #368
=> Using startDragAndDrop instead of startDrag on Android sdk24 and above

super_native_extensions/rust/src/linux/clipboard_async.rs
fix the crash when clipboard is empty (After system restart)
```
(example:19442): Gtk-CRITICAL **: 16:30:54.677: gtk_targets_include_text: assertion 'targets != NULL || n_targets == 0' failed
thread '<unnamed>' panicked at library/core/src/panicking.rs:220:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
0:     0x72ac33718085 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
1:     0x72ac33718085 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
at …
```
=> fix: paste caused crash when clipboard is empty on linux 

super_native_extensions/rust/src/linux/common.rs, super_native_extensions/rust/src/linux/drag.rs, super_native_extensions/rust/src/linux/menu.rs
Fixes https://github.com/superlistapp/super_native_extensions/issues/403
https://docs.gtk.org/gdk3/struct.EventButton.html
> Used for button press and button release events. The type field will be one of GDK_BUTTON_PRESS, GDK_2BUTTON_PRESS, GDK_3BUTTON_PRESS or GDK_BUTTON_RELEASE,
when event is `DoubleButtonPress` or `TripleButtonPress`, there is an panic occur.
=> fix: synthesize_button_up might cause crash on Linux

super_native_extensions/lib/src/web/drop.dart, super_native_extensions/test/src/web/drop_test/listeners_empty_by_default_test.dart, super_native_extensions/test/src/web/drop_test/save_listeners_for_removal_test.dart, super_native_extensions/test/src/web/drop_test/should_replace_listeners_on_reinitialization.dart
**The problem**
I noticed that on Web DOM listeners are added again on each reload/restart of the app and, during development, the number of events increased rapidly.
https://github.com/user-attachments/assets/64d9217e-1057-4060-8f74-c496395462eb
https://github.com/user-attachments/assets/bbea0cfe-c022-4a92-9a59-3f2367ed14c3
**The solution**
We can't account for it in dart land very easily, because even the dart context is thrown away and not even singletons survive. This is relevant because the listeners need to be saved somewhere in order to be removed later.
My solution is to attach the array of listeners as a DOM property, so that in the next initialization we can retrieve and remove them all.
**Bonus**
Tests were added for this. Just run:
```sh
flutter test --platform chrome
```
=> fix: Avoid adding duplicate listeners for drag-n-drop on the web

super_clipboard/example/pubspec.lock, super_context_menu/example/pubspec.lock, super_drag_and_drop/example/pubspec.lock, super_keyboard_layout/example/pubspec.lock, super_native_extensions/lib/src/clipboard_events.dart, super_native_extensions/lib/src/clipboard_reader.dart, super_native_extensions/lib/src/clipboard_writer.dart, super_native_extensions/lib/src/data_provider_manager.dart, super_native_extensions/lib/src/drag.dart, super_native_extensions/lib/src/drop.dart, super_native_extensions/lib/src/hot_key.dart, super_native_extensions/lib/src/keyboard_layout.dart, super_native_extensions/lib/src/menu.dart, super_native_extensions/lib/src/reader_manager.dart, super_native_extensions/lib/src/widget_snapshot/widget_snapshotter.dart
This PR replaces all `dart.library.js` conditional imports with `dart.library.js_interop` to make it compatible with Wasm.
Potentially fixes #432
=> Replace `dart.library.js` with `dart.library.js_interop`.

.github/workflows/precompile_binaries.yml
- Updates all Linux workflows to run on Ubuntu 22.04 as 20.04 is being deprecated
- Adds docker based compilation to precompile aarch64-unknown-linux-gnu and riscv64gc-unknown-linux-gnu
=> feat: updated precompile binaries workflow

super_native_extensions/lib/src/web/clipboard_events.dart
Fixes https://github.com/superlistapp/super_native_extensions/issues/507
This happens because the dom listeners are not unregisterd at hot reload. The correct way for this would be if flutter exposed `registerHotRestartListener` so we could have proper cleanup, but that's not the case. As a workaround we can store previous listeners in `window` object and unregister them during initialization.
=> fix[web]: unregister previously registered clipboard event listeners
